import { expect, it, vi } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import Panel from '../components/canvas-response-settings.vue'

const initial = () => ({conversationId:'c1',scope:'conversation',schemaVersion:1,revision:0,overrides:{},effective:{agency:'protect',style:'card',perspective:'card',length:'auto',pace:'natural'}})
it('preserves independent axes, clears hidden custom text and uses server readback', async () => {
 const load=vi.fn().mockResolvedValue(initial())
 const save=vi.fn().mockImplementation(async (_id, rev, patch)=>({...initial(),revision:rev+1,overrides:Object.fromEntries(Object.entries(patch).filter(([,v])=>v!==null))}))
 const wrapper=mount(Panel,{props:{conversationId:'c1',load,save,t:(k:string)=>k,confirm:vi.fn().mockResolvedValue(true)}})
 await flushPromises()
 await wrapper.get('[data-axis="agency"][data-value="coauthor"]').trigger('click')
 await wrapper.get('[data-axis="perspective"][data-value="second_user"]').trigger('click')
 await wrapper.get('[data-axis="style"][data-value="custom"]').trigger('click')
 await wrapper.get('textarea').setValue('Sparse prose')
 await wrapper.get('[data-axis="style"][data-value="plain"]').trigger('click')
 await wrapper.get('[data-action="save"]').trigger('click');await flushPromises()
 expect(save).toHaveBeenCalledWith('c1',0,expect.objectContaining({agency:'coauthor',perspective:'second_user',style:'plain',customStyle:null}))
 expect(wrapper.find('textarea').exists()).toBe(false)
 expect(wrapper.get('[data-action="save"]').attributes('disabled')).toBeDefined()
})
it('keeps draft on conflict and never saves assumed defaults after failed load', async()=>{
 const load=vi.fn().mockRejectedValue(new Error('offline'))
 const save=vi.fn().mockRejectedValue({statusCode:409})
 const wrapper=mount(Panel,{props:{conversationId:'c1',load,save,t:(k:string)=>k,confirm:vi.fn().mockResolvedValue(true)}})
 await flushPromises()
 expect(wrapper.find('[data-action="save"]').exists()).toBe(false)
 load.mockResolvedValue(initial())
 await wrapper.get('[data-action="reload"]').trigger('click');await flushPromises()
 await wrapper.get('[data-axis="agency"][data-value="assist"]').trigger('click')
 await wrapper.get('[data-action="save"]').trigger('click');await flushPromises()
 expect(wrapper.get('[role="alert"]').text()).toContain('conflict')
 expect(wrapper.get('[data-axis="agency"][data-value="assist"]').attributes('aria-pressed')).toBe('true')
})
it('keeps edits when close is cancelled and validates Unicode style length', async()=>{
 const confirm=vi.fn().mockResolvedValue(false)
 const wrapper=mount(Panel,{props:{conversationId:'c1',load:async()=>initial(),save:vi.fn(),t:(k:string)=>k,confirm}})
 await flushPromises()
 await wrapper.get('[data-axis="style"][data-value="custom"]').trigger('click')
 await wrapper.get('textarea').setValue('🌙'.repeat(1000))
 expect(wrapper.get('[data-action="save"]').attributes('disabled')).toBeUndefined()
 expect(await (wrapper.vm as any).mayClose()).toBe(false)
 await wrapper.get('textarea').setValue('🌙'.repeat(1001))
 expect(wrapper.get('[data-action="save"]').attributes('disabled')).toBeDefined()
 expect(wrapper.get('textarea').element.value.length).toBe(2002)
})
